# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Efficient Grid
email: efficient-grid@aerosol.me
description: >
  Efficient LESS flexbox grid system
baseurl: "/efficient-grid"
#url: "http://yourdomain.com"
#twitter_username: jekyllrb
github_username: BillyBlaze

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [node_modules]

collections:
- sections

defaults:
  - scope:
      path: "_sections"
      type: sections
    values:
      layout: sections
